[cpu]
core=normal
cycles=fixed 20000

[mixer]
nosound=false
rate=49716
blocksize=1024
prebuffer=25

[midi]
mpu401=none
mididevice=none

[sblaster]
sbtype=sb16
sbbase=220
irq=7
dma=1
hdma=5
sbmixer=true
oplmode=opl3
oplemu=nuked
oplrate=49716

[speaker]
pcspeaker=false
tandy=off
disney=false
