#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include "ml_assembly.h"

typedef struct {
    int bg, panel, accent1, accent2, accent3, line;
    const char *name;
} theme_t;

static const theme_t themes[] = {
    {0, 1, 11, 13, 14, 15, "NEON"},
    {0, 8, 12, 14, 10, 15, "FIRE"},
    {1, 3, 11, 15, 10, 14, "CYAN"},
    {0, 5, 13, 11, 12, 15, "MAGENTA"}
};

static int clampi(int v, int lo, int hi) {
    if (v < lo) return lo;
    if (v > hi) return hi;
    return v;
}

static void fail(const char *msg) {
    fprintf(stderr, "MLASM_BRIDGE=FAIL\nREASON=%s\n", msg);
    exit(2);
}
int main(int argc, char **argv) {
    if (argc != 2) fail("usage: mlasm_scene OUTPUT_INC");
    if (ml_init() != ML_SUCCESS) fail("ml_init");
    if (!ml_check_cpu_support()) fail("cpu_support");

    ml_vector_t *features = ml_vector_create(6);
    ml_matrix_t *theme_w = ml_matrix_create(4, 6);
    ml_vector_t *logits = ml_vector_create(4);
    ml_vector_t *probs = ml_vector_create(4);
    if (!features || !theme_w || !logits || !probs) fail("alloc_theme");

    const float fv[6] = {1.0f, 0.92f, 0.74f, 0.88f, 0.61f, 0.97f};
    const float tw[4][6] = {
        {0.9f, 0.8f, 0.5f, 0.9f, 0.2f, 1.0f},
        {0.6f, 0.3f, 1.0f, 0.7f, 0.9f, 0.5f},
        {0.8f, 1.0f, 0.4f, 0.8f, 0.4f, 0.9f},
        {0.7f, 0.6f, 0.6f, 1.0f, 0.5f, 0.8f}
    };

    for (size_t i = 0; i < 6; ++i) ml_vector_set(features, i, fv[i]);
    for (size_t r = 0; r < 4; ++r)
        for (size_t c = 0; c < 6; ++c)
            ml_matrix_set(theme_w, r, c, tw[r][c]);

    if (ml_matrix_vector_mul(theme_w, features, logits) != ML_SUCCESS)
        fail("theme_matvec");
    if (ml_activation_softmax(logits, probs) != ML_SUCCESS)
        fail("theme_softmax");
    size_t theme_idx = ml_vector_argmax(probs);
    ml_vector_t *phase = ml_vector_create(4);
    ml_matrix_t *wave_w = ml_matrix_create(8, 4);
    ml_vector_t *wave = ml_vector_create(8);
    if (!phase || !wave_w || !wave) fail("alloc_wave");

    const float pv[4] = {1.0f, 0.55f, -0.45f, 0.80f};
    const float ww[8][4] = {
        {-1.0f, 0.2f, 0.1f, 0.0f},
        {-0.7f, 0.5f, 0.1f, 0.1f},
        {-0.2f, 0.8f, 0.2f, 0.1f},
        { 0.3f, 0.8f, 0.3f, 0.1f},
        { 0.8f, 0.4f, 0.2f, 0.1f},
        { 1.0f,-0.1f, 0.1f, 0.0f},
        { 0.5f,-0.6f, 0.1f, 0.1f},
        {-0.2f,-0.8f, 0.2f, 0.1f}
    };

    for (size_t i = 0; i < 4; ++i) ml_vector_set(phase, i, pv[i]);
    for (size_t r = 0; r < 8; ++r)
        for (size_t c = 0; c < 4; ++c)
            ml_matrix_set(wave_w, r, c, ww[r][c]);

    if (ml_matrix_vector_mul(wave_w, phase, wave) != ML_SUCCESS)
        fail("wave_matvec");

    int wave_y[8];
    for (size_t i = 0; i < 8; ++i) {
        float v = ml_vector_get(wave, i);
        wave_y[i] = clampi((int)lrintf(v * 4.0f), -5, 5);
    }
    FILE *f = fopen(argv[1], "wb");
    if (!f) fail("open_output");
    const theme_t *t = &themes[theme_idx];

    fprintf(f, "; generated by MLAsm bridge\n");
    fprintf(f, "%%define THEME_BG %d\n", t->bg);
    fprintf(f, "%%define THEME_PANEL %d\n", t->panel);
    fprintf(f, "%%define THEME_ACCENT1 %d\n", t->accent1);
    fprintf(f, "%%define THEME_ACCENT2 %d\n", t->accent2);
    fprintf(f, "%%define THEME_ACCENT3 %d\n", t->accent3);
    fprintf(f, "%%define THEME_LINE %d\n", t->line);
    for (int i = 0; i < 8; ++i)
        fprintf(f, "%%define WAVE_%d %d\n", i, wave_y[i]);
    fclose(f);

    printf("MLASM_BRIDGE=PASS\n");
    printf("MLASM_VERSION=%s\n", ml_get_version());
    printf("CPU_SUPPORTED=YES\n");
    printf("THEME=%s\n", t->name);
    for (size_t i = 0; i < 4; ++i)
        printf("THEME_PROB_%zu=%.6f\n", i, ml_vector_get(probs, i));
    printf("WAVE=%d,%d,%d,%d,%d,%d,%d,%d\n",
           wave_y[0], wave_y[1], wave_y[2], wave_y[3],
           wave_y[4], wave_y[5], wave_y[6], wave_y[7]);
    printf("OUTPUT=%s\n", argv[1]);

    ml_vector_free(wave);
    ml_matrix_free(wave_w);
    ml_vector_free(phase);
    ml_vector_free(probs);
    ml_vector_free(logits);
    ml_matrix_free(theme_w);
    ml_vector_free(features);
    ml_cleanup();
    return 0;
}
