#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <stdbool.h>
#include "ml_assembly.h"

#define THEME_FEATURE_DIM 6u
#define THEME_CLASS_DIM   4u
#define WAVE_PHASE_DIM    4u
#define WAVE_OUT_DIM      8u
#define WAVE_SCALE        4.0f
#define WAVE_CLAMP_MIN   (-5.0f)
#define WAVE_CLAMP_MAX    5.0f

typedef struct {
    int bg, panel, accent1, accent2, accent3, line;
    const char *name;
} theme_t;

static const theme_t themes[THEME_CLASS_DIM] = {
    {0, 1, 11, 13, 14, 15, "NEON"},
    {0, 8, 12, 14, 10, 15, "FIRE"},
    {1, 3, 11, 15, 10, 14, "CYAN"},
    {0, 5, 13, 11, 12, 15, "MAGENTA"}
};

static int write_scene(FILE *f, const theme_t *theme,
                       const int wave_y[WAVE_OUT_DIM]) {
    if (fprintf(f, "; generated by MLAsm bridge\n") < 0) return 0;
    if (fprintf(f, "%%define THEME_BG %d\n", theme->bg) < 0) return 0;
    if (fprintf(f, "%%define THEME_PANEL %d\n", theme->panel) < 0) return 0;
    if (fprintf(f, "%%define THEME_ACCENT1 %d\n", theme->accent1) < 0) return 0;
    if (fprintf(f, "%%define THEME_ACCENT2 %d\n", theme->accent2) < 0) return 0;
    if (fprintf(f, "%%define THEME_ACCENT3 %d\n", theme->accent3) < 0) return 0;
    if (fprintf(f, "%%define THEME_LINE %d\n", theme->line) < 0) return 0;
    for (size_t i = 0; i < WAVE_OUT_DIM; ++i) {
        if (fprintf(f, "%%define WAVE_%zu %d\n", i, wave_y[i]) < 0) return 0;
    }
    return 1;
}

int main(int argc, char **argv) {
    int exit_code = EXIT_FAILURE;
    const char *reason = "uninitialized";
    bool ml_ready = false;
    bool output_touched = false;
    FILE *f = NULL;

    ml_vector_t *features = NULL;
    ml_matrix_t *theme_w = NULL;
    ml_vector_t *logits = NULL;
    ml_vector_t *probs = NULL;
    ml_vector_t *phase = NULL;
    ml_matrix_t *wave_w = NULL;
    ml_vector_t *wave = NULL;

    if (argc != 2) {
        fprintf(stderr,
                "STATE_IN=0\nSTATE_TRANSITION=0\nSTATE_OUT=0\n"
                "MLASM_BRIDGE=FAIL\nREASON=usage\n");
        return EXIT_FAILURE;
    }

    printf("STATE_IN=0\n");

    if (ml_init() != ML_SUCCESS) {
        reason = "ml_init";
        goto cleanup;
    }
    ml_ready = true;

    if (!ml_check_cpu_support()) {
        reason = "cpu_support";
        goto cleanup;
    }

    features = ml_vector_create(THEME_FEATURE_DIM);
    theme_w = ml_matrix_create(THEME_CLASS_DIM, THEME_FEATURE_DIM);
    logits = ml_vector_create(THEME_CLASS_DIM);
    probs = ml_vector_create(THEME_CLASS_DIM);
    if (!features || !theme_w || !logits || !probs) {
        reason = "alloc_theme";
        goto cleanup;
    }

    const float fv[THEME_FEATURE_DIM] = {
        1.0f, 0.92f, 0.74f, 0.88f, 0.61f, 0.97f
    };
    const float tw[THEME_CLASS_DIM][THEME_FEATURE_DIM] = {
        {0.9f, 0.8f, 0.5f, 0.9f, 0.2f, 1.0f},
        {0.6f, 0.3f, 1.0f, 0.7f, 0.9f, 0.5f},
        {0.8f, 1.0f, 0.4f, 0.8f, 0.4f, 0.9f},
        {0.7f, 0.6f, 0.6f, 1.0f, 0.5f, 0.8f}
    };

    for (size_t i = 0; i < THEME_FEATURE_DIM; ++i) {
        if (ml_vector_set(features, i, fv[i]) != ML_SUCCESS) {
            reason = "set_theme_feature";
            goto cleanup;
        }
    }
    for (size_t r = 0; r < THEME_CLASS_DIM; ++r) {
        for (size_t c = 0; c < THEME_FEATURE_DIM; ++c) {
            if (ml_matrix_set(theme_w, r, c, tw[r][c]) != ML_SUCCESS) {
                reason = "set_theme_weight";
                goto cleanup;
            }
        }
    }

    if (ml_matrix_vector_mul(theme_w, features, logits) != ML_SUCCESS) {
        reason = "theme_matvec";
        goto cleanup;
    }
    if (ml_activation_softmax(logits, probs) != ML_SUCCESS) {
        reason = "theme_softmax";
        goto cleanup;
    }

    double probability_sum = 0.0;
    for (size_t i = 0; i < THEME_CLASS_DIM; ++i) {
        const float p = ml_vector_get(probs, i);
        if (!isfinite(p) || p < 0.0f) {
            reason = "theme_probability_nonfinite";
            goto cleanup;
        }
        probability_sum += (double)p;
    }
    if (!isfinite(probability_sum) || probability_sum <= 0.0) {
        reason = "theme_probability_sum";
        goto cleanup;
    }

    const size_t theme_idx = ml_vector_argmax(probs);
    if (theme_idx >= THEME_CLASS_DIM) {
        reason = "theme_argmax_oob";
        goto cleanup;
    }

    phase = ml_vector_create(WAVE_PHASE_DIM);
    wave_w = ml_matrix_create(WAVE_OUT_DIM, WAVE_PHASE_DIM);
    wave = ml_vector_create(WAVE_OUT_DIM);
    if (!phase || !wave_w || !wave) {
        reason = "alloc_wave";
        goto cleanup;
    }

    const float pv[WAVE_PHASE_DIM] = {1.0f, 0.55f, -0.45f, 0.80f};
    const float ww[WAVE_OUT_DIM][WAVE_PHASE_DIM] = {
        {-1.0f, 0.2f, 0.1f, 0.0f},
        {-0.7f, 0.5f, 0.1f, 0.1f},
        {-0.2f, 0.8f, 0.2f, 0.1f},
        { 0.3f, 0.8f, 0.3f, 0.1f},
        { 0.8f, 0.4f, 0.2f, 0.1f},
        { 1.0f,-0.1f, 0.1f, 0.0f},
        { 0.5f,-0.6f, 0.1f, 0.1f},
        {-0.2f,-0.8f, 0.2f, 0.1f}
    };

    for (size_t i = 0; i < WAVE_PHASE_DIM; ++i) {
        if (ml_vector_set(phase, i, pv[i]) != ML_SUCCESS) {
            reason = "set_wave_phase";
            goto cleanup;
        }
    }
    for (size_t r = 0; r < WAVE_OUT_DIM; ++r) {
        for (size_t c = 0; c < WAVE_PHASE_DIM; ++c) {
            if (ml_matrix_set(wave_w, r, c, ww[r][c]) != ML_SUCCESS) {
                reason = "set_wave_weight";
                goto cleanup;
            }
        }
    }

    if (ml_matrix_vector_mul(wave_w, phase, wave) != ML_SUCCESS) {
        reason = "wave_matvec";
        goto cleanup;
    }

    int wave_y[WAVE_OUT_DIM];
    for (size_t i = 0; i < WAVE_OUT_DIM; ++i) {
        const float v = ml_vector_get(wave, i);
        if (!isfinite(v)) {
            reason = "wave_nonfinite";
            goto cleanup;
        }

        float scaled = v * WAVE_SCALE;
        if (!isfinite(scaled)) {
            reason = "wave_scale_nonfinite";
            goto cleanup;
        }
        if (scaled < WAVE_CLAMP_MIN) scaled = WAVE_CLAMP_MIN;
        if (scaled > WAVE_CLAMP_MAX) scaled = WAVE_CLAMP_MAX;
        wave_y[i] = (int)lrintf(scaled);
    }

    f = fopen(argv[1], "wb");
    if (!f) {
        reason = "open_output";
        goto cleanup;
    }
    output_touched = true;

    const theme_t *theme = &themes[theme_idx];
    if (!write_scene(f, theme, wave_y) || fflush(f) != 0 || ferror(f)) {
        reason = "write_output";
        goto cleanup;
    }
    if (fclose(f) != 0) {
        f = NULL;
        reason = "close_output";
        goto cleanup;
    }
    f = NULL;
    output_touched = false;

    printf("STATE_TRANSITION=1\n");
    printf("MLASM_BRIDGE=PASS\n");
    printf("MLASM_VERSION=%s\n", ml_get_version());
    printf("CPU_SUPPORTED=1\n");
    printf("THEME_INDEX=%zu\n", theme_idx);
    printf("THEME=%s\n", theme->name);
    for (size_t i = 0; i < THEME_CLASS_DIM; ++i) {
        printf("THEME_PROB_%zu=%.6f\n", i, ml_vector_get(probs, i));
    }
    printf("WAVE=%d,%d,%d,%d,%d,%d,%d,%d\n",
           wave_y[0], wave_y[1], wave_y[2], wave_y[3],
           wave_y[4], wave_y[5], wave_y[6], wave_y[7]);
    printf("OUTPUT=%s\n", argv[1]);
    printf("STATE_OUT=0\n");
    exit_code = EXIT_SUCCESS;

cleanup:
    if (f && fclose(f) != 0 && exit_code == EXIT_SUCCESS) {
        exit_code = EXIT_FAILURE;
        reason = "close_output_cleanup";
    }
    if (output_touched) {
        remove(argv[1]);
    }

    if (wave) ml_vector_free(wave);
    if (wave_w) ml_matrix_free(wave_w);
    if (phase) ml_vector_free(phase);
    if (probs) ml_vector_free(probs);
    if (logits) ml_vector_free(logits);
    if (theme_w) ml_matrix_free(theme_w);
    if (features) ml_vector_free(features);
    if (ml_ready) ml_cleanup();

    if (exit_code != EXIT_SUCCESS) {
        fprintf(stderr,
                "STATE_TRANSITION=0\nSTATE_OUT=0\n"
                "MLASM_BRIDGE=FAIL\nREASON=%s\n",
                reason);
    }
    return exit_code;
}
