#define _POSIX_C_SOURCE 200809L
#include <errno.h>
#include <fenv.h>
#include <locale.h>
#include <math.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <unistd.h>
#include "ml_assembly.h"

/* MLAsm remains the inference backend. This file emits NASM constants only. */
enum { EXIT_USAGE=2, EXIT_SETUP=3, EXIT_ALLOC=4, EXIT_API=5,
       EXIT_RESULT=6, EXIT_OUTPUT=7 };

typedef struct {
    int bg, panel, accent1, accent2, accent3, line;
    const char *name;
} theme_t;

static const theme_t themes[] = {
    {0, 1, 11, 13, 14, 15, "NEON"},
    {0, 8, 12, 14, 10, 15, "FIRE"},
    {1, 3, 11, 15, 10, 14, "CYAN"},
    {0, 5, 13, 11, 12, 15, "MAGENTA"}
};

static int emit_scene(FILE *f, const theme_t *t, const int wave[8]) {
    if (fprintf(f, "; generated by MLAsm bridge\n") < 0 ||
        fprintf(f, "%%define THEME_BG %d\n", t->bg) < 0 ||
        fprintf(f, "%%define THEME_PANEL %d\n", t->panel) < 0 ||
        fprintf(f, "%%define THEME_ACCENT1 %d\n", t->accent1) < 0 ||
        fprintf(f, "%%define THEME_ACCENT2 %d\n", t->accent2) < 0 ||
        fprintf(f, "%%define THEME_ACCENT3 %d\n", t->accent3) < 0 ||
        fprintf(f, "%%define THEME_LINE %d\n", t->line) < 0)
        return -1;
    for (size_t i=0; i<8; ++i)
        if (fprintf(f, "%%define WAVE_%zu %d\n", i, wave[i]) < 0) return -1;
    return 0;
}

/* Complete file or no replacement: never truncate the destination on failure.
 * Parent directory is caller-owned/trusted. This is not a hostile-directory API.
 */
static int write_scene(const char *path, const theme_t *theme, const int wave[8]) {
    struct stat st;
    if (lstat(path, &st) == 0) {
        if (!S_ISREG(st.st_mode)) return EXIT_OUTPUT;
    } else if (errno != ENOENT) return EXIT_OUTPUT;
    size_t length=strlen(path);
    if (length==0 || length>SIZE_MAX-12) return EXIT_OUTPUT;
    size_t capacity=length+12;
    char *temporary=malloc(capacity);
    if (!temporary) return EXIT_ALLOC;
    int n=snprintf(temporary,capacity,"%s.tmp.XXXXXX",path);
    if (n<0 || (size_t)n>=capacity) { free(temporary); return EXIT_OUTPUT; }
    int fd=mkstemp(temporary);
    if (fd<0) { free(temporary); return EXIT_OUTPUT; }
    int result=EXIT_OUTPUT;
    FILE *file=fdopen(fd,"wb");
    if (file) {
        int written=emit_scene(file,theme,wave);
        int closed=fclose(file); /* includes buffered/partial-write errors */
        if (written==0 && closed==0 && rename(temporary,path)==0) result=0;
    } else {
        (void)close(fd); /* already failing; this cannot produce success */
    }
    if (result!=0 && unlink(temporary)!=0 && errno!=ENOENT) result=EXIT_OUTPUT;
    free(temporary);
    return result;
}

int main(int argc, char **argv) {
    int result=EXIT_USAGE;
    const char *reason="usage: mlasm_scene OUTPUT_INC";
    int initialized=0;
    ml_vector_t *features=NULL, *logits=NULL, *probs=NULL, *phase=NULL, *wave=NULL;
    ml_matrix_t *theme_w=NULL, *wave_w=NULL;
    if (argc!=2 || argv[1][0]=='\0') goto cleanup;
    result=EXIT_SETUP; reason="locale_or_rounding";
    if (!setlocale(LC_NUMERIC,"C") || fesetround(FE_TONEAREST)!=0) goto cleanup;
#if defined(__x86_64__) && (defined(__GNUC__) || defined(__clang__))
    __builtin_cpu_init();
    reason="cpu_requires_avx2_and_fma";
    if (!__builtin_cpu_supports("avx2") || !__builtin_cpu_supports("fma")) goto cleanup;
#else
#error "MLAsm bridge requires an x86-64 GCC/Clang host"
#endif
    reason="cpu_support";
    if (!ml_check_cpu_support()) goto cleanup;
    reason="ml_init";
    if (ml_init()!=ML_SUCCESS) goto cleanup;
    initialized=1;
    result=EXIT_ALLOC; reason="allocation";
    features=ml_vector_create(6); theme_w=ml_matrix_create(4,6);
    logits=ml_vector_create(4); probs=ml_vector_create(4);
    phase=ml_vector_create(4); wave_w=ml_matrix_create(8,4); wave=ml_vector_create(8);
    if (!features || !theme_w || !logits || !probs || !phase || !wave_w || !wave) goto cleanup;

    const float fv[6] = {1.0f, 0.92f, 0.74f, 0.88f, 0.61f, 0.97f};
    const float tw[4][6] = {
        {0.9f, 0.8f, 0.5f, 0.9f, 0.2f, 1.0f},
        {0.6f, 0.3f, 1.0f, 0.7f, 0.9f, 0.5f},
        {0.8f, 1.0f, 0.4f, 0.8f, 0.4f, 0.9f},
        {0.7f, 0.6f, 0.6f, 1.0f, 0.5f, 0.8f}
    };

    const float pv[4] = {1.0f, 0.55f, -0.45f, 0.80f};
    const float ww[8][4] = {
        {-1.0f, 0.2f, 0.1f, 0.0f},
        {-0.7f, 0.5f, 0.1f, 0.1f},
        {-0.2f, 0.8f, 0.2f, 0.1f},
        { 0.3f, 0.8f, 0.3f, 0.1f},
        { 0.8f, 0.4f, 0.2f, 0.1f},
        { 1.0f,-0.1f, 0.1f, 0.0f},
        { 0.5f,-0.6f, 0.1f, 0.1f},
        {-0.2f,-0.8f, 0.2f, 0.1f}
    };

    result=EXIT_API; reason="vector_or_matrix_set";
    for (size_t i=0; i<6; ++i)
        if (ml_vector_set(features,i,fv[i])!=ML_SUCCESS) goto cleanup;
    for (size_t row=0; row<4; ++row)
        for (size_t col=0; col<6; ++col)
            if (ml_matrix_set(theme_w,row,col,tw[row][col])!=ML_SUCCESS) goto cleanup;
    for (size_t i=0; i<4; ++i)
        if (ml_vector_set(phase,i,pv[i])!=ML_SUCCESS) goto cleanup;
    for (size_t row=0; row<8; ++row)
        for (size_t col=0; col<4; ++col)
            if (ml_matrix_set(wave_w,row,col,ww[row][col])!=ML_SUCCESS) goto cleanup;
    reason="theme_matvec";
    if (ml_matrix_vector_mul(theme_w,features,logits)!=ML_SUCCESS) goto cleanup;
    reason="theme_softmax";
    if (ml_activation_softmax(logits,probs)!=ML_SUCCESS) goto cleanup;
    size_t theme_idx=ml_vector_argmax(probs);
    result=EXIT_RESULT; reason="theme_index";
    if (theme_idx>=sizeof(themes)/sizeof(themes[0])) goto cleanup;
    float probabilities[4];
    for (size_t i=0; i<4; ++i) {
        probabilities[i]=ml_vector_get(probs,i);
        reason="nonfinite_or_invalid_probability";
        if (!isfinite(probabilities[i]) || probabilities[i]<0.0f || probabilities[i]>1.0f) goto cleanup;
    }
    result=EXIT_API; reason="wave_matvec";
    if (ml_matrix_vector_mul(wave_w,phase,wave)!=ML_SUCCESS) goto cleanup;
    int wave_y[8];
    for (size_t i=0; i<8; ++i) {
        float v=ml_vector_get(wave,i);
        result=EXIT_RESULT; reason="nonfinite_wave";
        if (!isfinite(v)) goto cleanup;
        /* Clamp BEFORE multiplication/conversion; even FLT_MAX is safe. */
        wave_y[i]=v<=-1.25f ? -5 : v>=1.25f ? 5 : (int)lrintf(v*4.0f);
    }
    const char *version=ml_get_version();
    result=EXIT_RESULT; reason="invalid_version";
    if (!version || strnlen(version,64)==64) goto cleanup;
    const theme_t *theme=&themes[theme_idx];
    result=write_scene(argv[1],theme,wave_y); reason="output_commit";
    if (result!=0) goto cleanup;
    result=EXIT_OUTPUT; reason="stdout";
    if (printf("MLASM_VERSION=%s\nCPU_SUPPORTED=YES\nTHEME=%s\n",version,theme->name)<0) goto cleanup;
    for (size_t i=0; i<4; ++i)
        if (printf("THEME_PROB_%zu=%.6f\n",i,(double)probabilities[i])<0) goto cleanup;
    if (printf("WAVE=%d,%d,%d,%d,%d,%d,%d,%d\nOUTPUT_WRITTEN=YES\n",
               wave_y[0],wave_y[1],wave_y[2],wave_y[3],wave_y[4],wave_y[5],wave_y[6],wave_y[7])<0 ||
        fflush(stdout)!=0 || puts("MLASM_BRIDGE=PASS")==EOF || fflush(stdout)!=0) goto cleanup;
    result=0;
cleanup:
    if (wave) ml_vector_free(wave);
    if (wave_w) ml_matrix_free(wave_w);
    if (phase) ml_vector_free(phase);
    if (probs) ml_vector_free(probs);
    if (logits) ml_vector_free(logits);
    if (theme_w) ml_matrix_free(theme_w);
    if (features) ml_vector_free(features);
    if (initialized) ml_cleanup();
    if (result!=0) {
        /* A broken diagnostic stream cannot turn a failed operation into success. */
        (void)fprintf(stderr,"MLASM_BRIDGE=FAIL\nREASON=%s\nEXIT_CODE=%d\n",reason,result);
    }
    return result;
}
